version: '3.8'

services:
  web:
    build: .
    container_name: qa_backend
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head; uvicorn main:app --host 0.0.0.0 --port 8001 --reload'
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8001:8001"
    environment:
      - DB_HOST=qa_db
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
    env_file:
      - ./.env
    networks:
      - q_a_network
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: qa_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - ./.env
    networks:
      - q_a_network

networks:
  q_a_network:
    driver: bridge
volumes:
  postgres_data: